### PR TITLE
hide runtime files

### PR DESCRIPTION
**Pull request by zacronos**
runs nginx within a nginx/ subdirectory, in order to group all the random files and folders nginx creates

### CODE REVIEW

**Comment by nmccready** [comment]
Is the specs expected to fail? IE needs cache cleared?

**Comment by zacronos** [comment]
there are no tests on this repo -- but see https://github.com/realtymaps/map/pull/618 before you do anything here

**Comment by nmccready** [comment]
Anyway we can disable circleci from reporting errors then?

**Comment by zacronos** [comment]
I've now configured CircleCI to stop watching this project.  I'm not sure why it ever was in the first place.

**Pull request merged**
